name: CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      # ----------------------------------------
      # Checkout
      # ----------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------------------
      # Setup .NET
      # ----------------------------------------
      # TODO:
      # 実際の.NETバージョンに変更してください。
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.300'

      # ----------------------------------------
      # Setup Python
      # ----------------------------------------
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      # ----------------------------------------
      # Publish
      # ----------------------------------------
      - name: Publish compiler
        shell: cmd
        run: |
          call shells\publish-compiler.cmd

      # ----------------------------------------
      # Package
      # ----------------------------------------
      - name: Package compiler
        shell: pwsh
        run: |
          python shells/package-compiler.py

      # ----------------------------------------
      # Upload build artifacts
      # ----------------------------------------
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: compiler-packages
          path: |
            package/**/*.zip
          if-no-files-found: error

  test:
    name: Test - ${{ matrix.name }}

    needs: build

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-x64
            runner: windows-latest
            rid: win-x64

          - name: linux-x64
            runner: ubuntu-24.04
            rid: linux-x64

          - name: linux-arm64
            runner: ubuntu-24.04-arm
            rid: linux-arm64

          - name: osx-arm64
            runner: macos-15
            rid: osx-arm64

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Show environment
        shell: bash
        run: |
          echo "Name: ${{ matrix.name }}"
          echo "RID:  ${{ matrix.rid }}"
          echo "Runner: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"

          uname -a

      - name: Download packages
        uses: actions/download-artifact@v5
        with:
          name: compiler-packages
          path: artifacts

      - name: List downloaded files
        shell: bash
        run: |
          echo "=== Downloaded artifacts ==="
          find artifacts -type f
